### ISSUE TITLE
not really work?

### ISSUE THREAD

**Issue by mazmamad** [Wolf49406/DotaCameraHack#2]
allo i was using this before diretide update and i think it working, 

and u update the readme that this is Temporarily dead(?) .
so i can't use it now?

**Comment by Wolf49406** [comment]
Offsets in dll was changed. Well, i'll fix this today.
Also i'll remove auto-accept option bc now we have [this](https://github.com/Wolf49406/DotaAutoAccept)

**Comment by Wolf49406** [comment]
Fixed.
